import { GLOBAL_ROLES, TENANT_ROLES } from '@/modules/auth/roles';

export const PERMISSIONS = Object.freeze({
  TENANT_VIEW: 'tenant.view',
  TENANT_MANAGE: 'tenant.manage',
  TENANT_BLOCK: 'tenant.block',
  USER_GLOBAL_MANAGE: 'user.global.manage',
  USER_TENANT_MANAGE: 'user.tenant.manage',
  AUTH_SUPPORT: 'auth.support',
  CATALOG_MANAGE: 'catalog.manage',
  BILLING_GLOBAL_VIEW: 'billing.global.view',
  BILLING_POLICY_MANAGE: 'billing.policy.manage',
  CREDIT_VIEW: 'credit.view',
  CREDIT_MANAGE: 'credit.manage',
  CREDIT_ADJUST: 'credit.adjust',
  ASSESSMENT_CREATE: 'assessment.create',
  ASSESSMENT_VIEW_TENANT: 'assessment.view.tenant',
  ASSESSMENT_VIEW_SELF: 'assessment.view.self',
  REPORT_VIEW_TENANT: 'report.view.tenant',
  REPORT_VIEW_SHARED: 'report.view.shared',
  REPORT_VIEW_SELF: 'report.view.self',
  REPORT_VIEW_PRO: 'report.view.pro',
  REPORT_EXPORT: 'report.export',
  AUDIT_VIEW: 'audit.view',
  IMPERSONATE_TENANT: 'impersonate.tenant',
  SETTINGS_GLOBAL_MANAGE: 'settings.global.manage',
});

export const ENTITLEMENTS = Object.freeze({
  REPORT_PRO: 'report.pro',
  REPORT_EXPORT_PDF: 'report.export.pdf',
  REPORT_EXPORT_CSV: 'report.export.csv',
  CREDIT_ADJUST: 'credit.adjust',
  SUPPORT_SENSITIVE_REPORTS: 'support.report.sensitive',
});

export const ENTITLEMENT_TO_PERMISSIONS = Object.freeze({
  [ENTITLEMENTS.REPORT_PRO]: [PERMISSIONS.REPORT_VIEW_PRO],
  [ENTITLEMENTS.REPORT_EXPORT_PDF]: [PERMISSIONS.REPORT_EXPORT],
  [ENTITLEMENTS.REPORT_EXPORT_CSV]: [PERMISSIONS.REPORT_EXPORT],
  [ENTITLEMENTS.CREDIT_ADJUST]: [PERMISSIONS.CREDIT_ADJUST],
});

export const ROLE_PERMISSIONS = Object.freeze({
  [GLOBAL_ROLES.SUPER_ADMIN]: ['*'],
  [GLOBAL_ROLES.PLATFORM_ADMIN]: [
    PERMISSIONS.TENANT_VIEW,
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.USER_TENANT_MANAGE,
    PERMISSIONS.AUTH_SUPPORT,
    PERMISSIONS.BILLING_GLOBAL_VIEW,
    PERMISSIONS.ASSESSMENT_VIEW_TENANT,
    PERMISSIONS.REPORT_VIEW_TENANT,
    PERMISSIONS.AUDIT_VIEW,
  ],
  [TENANT_ROLES.TENANT_ADMIN]: [
    PERMISSIONS.TENANT_VIEW,
    PERMISSIONS.CREDIT_VIEW,
    PERMISSIONS.CREDIT_MANAGE,
    PERMISSIONS.USER_TENANT_MANAGE,
    PERMISSIONS.ASSESSMENT_CREATE,
    PERMISSIONS.ASSESSMENT_VIEW_TENANT,
    PERMISSIONS.REPORT_VIEW_TENANT,
    PERMISSIONS.REPORT_VIEW_SELF,
  ],
  [TENANT_ROLES.TENANT_USER]: [
    PERMISSIONS.TENANT_VIEW,
    PERMISSIONS.ASSESSMENT_CREATE,
    PERMISSIONS.ASSESSMENT_VIEW_TENANT,
    PERMISSIONS.REPORT_VIEW_SHARED,
    PERMISSIONS.REPORT_VIEW_SELF,
  ],
  [TENANT_ROLES.END_CUSTOMER]: [
    PERMISSIONS.ASSESSMENT_VIEW_SELF,
    PERMISSIONS.REPORT_VIEW_SELF,
  ],
});

